---
title: "Bookings Project"
author: "Group 13"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Let's import and understand the data
```{r}
bookings <- read.csv("bookings.csv")
summary(bookings)
str(bookings)
## This dataset is extracted from a hotel group and it explains its bookings and its characteristics. The main goal of this analysis is to optimize the reservations by predicting when the reservation will be canceled. This dataset consists of 32 variables that include integers and factors.

```


## 2. Data cleaning
```{r}
# 1. Solving NAs:
bookings$children <- ifelse(is.na(bookings$children),0,bookings$children)
bookings$stays_in_weekend_nights <- ifelse(is.na(bookings$stays_in_weekend_nights),0,bookings$stays_in_weekend_nights)
bookings$stays_in_week_nights <- ifelse(is.na(bookings$stays_in_week_nights),0,bookings$stays_in_week_nights)
bookings$reserved_room_type <- ifelse(is.na(bookings$reserved_room_type),0,bookings$reserved_room_type)
bookings$distribution_channel <- ifelse(is.na(bookings$distribution_channel),0,bookings$distribution_channel)


# 2. Simplyfing the dataset:
## A. There are 334 levels for the variable agent. We will keep only the top 5 levels.
bookings$agent <- as.character(bookings$agent)
bookings$agent.s <- ifelse(bookings$agent == "9", "9", ifelse(bookings$agent == "240", "240", ifelse(bookings$agent == "NULL", "NULL", ifelse(bookings$agent == "1", "1", ifelse(bookings$agent == "14", "14", "Others")))))
bookings$agent.s <- as.factor(bookings$agent.s)

## B. There are 353 levels for the variable company. We will keep only the top levels. NULL, 40, 223, 67, 45
bookings$company <- as.character(bookings$company)
bookings$company.s <- ifelse(bookings$company == "NULL", "NULL", ifelse(bookings$company == "40", "40", ifelse(bookings$company == "223", "223", ifelse(bookings$company == "67", "67", ifelse(bookings$company == "45", "45", "Others")))))
bookings$company.s <- as.factor(bookings$company.s)


## C. There are 178 levels for the variable country. We will group them by region.
# Note: most of the tourist come from Europe so we decided to focus on Europe 
levels(bookings$country) <- list( Southern_Europe= c("PRT","ESP","ITA"), Western_Europe =  c("GBR " , "IRL",  "FRA " ,  "CHE" , "BEL" ,  "NLD",  "LUX"), Cental_Europe = c("DEU",  "AUT" , "POL" ,  "HUN" , "CZE"), Northern_Europe = c("FIN" , "DNK", "SWE","NOR" ), Eastern_Europe= c("ROU","EST", "LTU","BGR", "UKR"), Eastern_Asia = c("CHN", "JPN", "KOR", "THA", "TWN","HKG "), Middle_East =c("ISR", "EGY", "JOR", "QAT", "OMN"), North_America = c("CN","MEX","USA"), South_America =c("BRA","ARG", "URY"))

bookings$country <- as.character(bookings$country)
bookings$country <- ifelse(is.na(bookings$country),"Rest of the World",bookings$country)
bookings$country <- as.factor(bookings$country)


## D. Groupign leading times into months 
bookings$lead_time<-ifelse(bookings$lead_time <= 31,"One Months", ifelse(bookings$lead_time > 31 & bookings$lead_time <= 62,"Two months", ifelse(bookings$lead_time > 62 & bookings$lead_time <= 93,"Three months", ifelse(bookings$lead_time > 93 & bookings$lead_time <= 124,"Four months", ifelse(bookings$lead_time > 124 & bookings$lead_time <= 155,"Five Months", ifelse(bookings$lead_time > 155 & bookings$lead_time <= 181, "Six weeks", "More than 6 months"))))))

bookings$lead_time <- as.factor(bookings$lead_time)

## E. Grouping number of week nights 
bookings$stays_in_week_nights <-ifelse(bookings$stays_in_week_nights <= 0,"0", ifelse(bookings$stays_in_week_nights > 0 & bookings$stays_in_week_nights <= 1,"1", ifelse(bookings$stays_in_week_nights > 1 & bookings$stays_in_week_nights <= 2, "2", ifelse(bookings$stays_in_week_nights > 2 & bookings$stays_in_week_nights <= 3,"3", ifelse(bookings$stays_in_week_nights > 3 & bookings$stays_in_week_nights <= 4,"4", ifelse(bookings$stays_in_week_nights > 4 & bookings$stays_in_week_nights <= 5, "5", ifelse(bookings$stays_in_week_nights > 5 & bookings$stays_in_week_nights <= 6, "6", ifelse(bookings$stays_in_week_nights > 6 & bookings$stays_in_week_nights <= 7, "7", ifelse(bookings$stays_in_week_nights > 7 & bookings$stays_in_week_nights <= 8, "8", ifelse(bookings$stays_in_week_nights > 8 & bookings$stays_in_week_nights <= 9, "9", "More than 9 nights"))))))))))
table(bookings$stays_in_week_nights)

bookings$stays_in_week_nights <- as.factor(bookings$stays_in_week_nights)

## F. Grouping number of weekend nights 
bookings$stays_in_weekend_nights <-ifelse(bookings$stays_in_weekend_nights <=0,"0", ifelse(bookings$stays_in_weekend_nights > 0 & bookings$stays_in_weekend_nights <= 1,"1", ifelse(bookings$stays_in_weekend_nights > 1 & bookings$stays_in_weekend_nights <= 2,"2", ifelse(bookings$stays_in_weekend_nights > 2 & bookings$stays_in_weekend_nights <= 3,"3", ifelse(bookings$stays_in_weekend_nights > 3 & bookings$stays_in_weekend_nights <= 4,"4", ifelse(bookings$stays_in_weekend_nightss > 4 &bookings$stays_in_weekend_nights <= 5, "5 ", "More than 5 nights"))))))

bookings$stays_in_weekend_nights <- as.factor(bookings$stays_in_weekend_nights)

## G. Turning the variables children and babys to a 0/1 if they have or not
#babies
bookings$babies <- as.character(bookings$babies)
bookings$babies.s <- ifelse(bookings$babies == "0", "No", "Yes")
bookings$babies.s <- as.factor(bookings$babies.s)

#children
bookings$children <- as.character(bookings$children)
bookings$children.s <- ifelse(bookings$children == "0", "No", "Yes")
bookings$children.s <- as.factor(bookings$children.s)

# 3. Column Elimination
## A. Deleting columns that have been replaced 
bookings$children <- NULL
bookings$babies <- NULL

## B. Deleting unnecesary columns
drops <- c("agent","company", "adr", "reservation_status_date", "assigned_room_type", "market_segment", "arrival_date_year", "arrival_date_day_of_month", "arrival_date_week_number", "arrival_date_month1", "reservation_status", "adults")
bookings <- bookings[ , !(names(bookings) %in% drops)]


# 4. Making dummy variables as we have multiple factors

bookings.dummy <- as.data.frame(model.matrix(~ . -1, bookings))
```

# 3. Preaparing data 
```{r}
# 1. Randomaze the data:
set.seed(65)
bookings.dummy <- bookings.dummy[sample(1:nrow(bookings.dummy)),]

bookings.dummy <- bookings.dummy[1:1000,]

# 2. Normalize the data:
normalize <- function(x) { 
  return((x - min(x)) / (max(x) - min(x)))
}
bookings.dummy.n <- as.data.frame(sapply(bookings.dummy, normalize))

bookings.dummy.n$stays_in_week_nights9 <- ifelse(is.na(bookings.dummy.n$stays_in_week_nights9),0,bookings.dummy.n$stays_in_week_nights9)

# 3. Build train and test datasets:
library(caTools)
set.seed(123)
split <- sample.split(bookings.dummy.n$is_canceled, SplitRatio = 0.7)
bookings_train <- subset(bookings.dummy.n, split == TRUE)
bookings_test <- subset(bookings.dummy.n, split == FALSE)

bookings_train_labels <- bookings_train[, 3]
bookings_test_labels <- bookings_test[, 3]

# 3.1. Making sure they have a similar/logic distribution
table(bookings_train_labels)
table(bookings_test_labels)

```


## 4. Exploring data 
### Graph 1
```{r}
# Exploring how many bookings are canceled and not  
graph1 <- plot(as.factor(bookings$is_canceled), main="How often customers cancel their bookings?", ylab="Number of cancelations",  xlab= "Is canceled", ylim = c(0,90000), col=c("green", "red"), legend.text = "0 = No, 1 = Yes", width=20)
graph1
```

### Graph 2
```{r}
# Exploring which month is the most popular for hotel visits
graph2 <- plot(bookings$arrival_date_month, main="Which month is the most popular?", ylab="Number of reservation",  xlab= "Month", las=2, names.arg= c("January", "February", "March", "April", "May", "June", "July", "August", "September","October", "November", "December"), ylim=c(0,15000))
```

### Graph 3
```{r}
library(ggplot2)
# Number of cancellations depending on the number of stays in weekend nights
graph3 <- ggplot(data = bookings[bookings$is_canceled == 1,], aes(stays_in_weekend_nights)) + geom_bar(aes(fill = ..count..)) + theme(axis.text.x = element_text(angle = 0, hjust = 0))
graph3
```

### Graph 4
```{r}
# Number of cancellations depending on the number of stays in week nights
graph4 <- ggplot(data = bookings[bookings$is_canceled == 1,], aes(stays_in_week_nights)) + geom_bar(aes(fill = ..count..)) + theme(axis.text.x = element_text(angle = 0, hjust = 0))
graph4
```

### Graph 5
```{r}
# Exploring the cancellations depending on the lead time
graph5 <- ggplot(data = bookings[bookings$is_canceled == 1,], aes(lead_time)) + geom_bar(aes(fill = ..count..)) + theme(axis.text.x = element_text(angle = 90, hjust = 0))
graph5
```

### Graph 6
```{r}
# Exploring the cancellations depending on the hotel
graph6 <- ggplot(data = bookings[bookings$is_canceled == 1,], aes(hotel)) + geom_bar(aes(fill = ..count..)) + theme(axis.text.x = element_text(angle = 0, hjust = 0))
graph6
```

### Graph 7
```{r}
# Number of cancellatiions per month
graph7 <- ggplot(data = bookings[bookings$is_canceled == 1,], aes(arrival_date_month)) + geom_bar(aes(fill = ..count..)) + theme(axis.text.x = element_text(angle = 90, hjust = 0))
graph7
```


## 5. Regression model
```{r}
### Performing stepwise selection to isolate most relevant factors
options(warn=-1)
training.omit <- na.omit(bookings_train)

model.null = glm(is_canceled ~ 1,
                 data=training.omit,
                 family = binomial(link="logit")
)

model.full = glm(is_canceled ~ .,
                 data=training.omit,
                 family = binomial(link="logit")
)

model1 = step(model.null,
     scope = list(upper=model.full),
     direction="both",
     test="Chisq",
     data=bookings_train,
     trace=FALSE)

summary(model1)
library(caret)

model1_pred = predict(model1, bookings_test)
binary = ifelse(model1_pred > 0.5, 1, 0)
confusionMatrix(as.factor(binary), as.factor(bookings_test_labels))
## With this model we obtain an accuracy of 80.33%.
```

```{r}
## Additional data cleaning
library(janitor)

bookings_train <- clean_names(bookings_train)
bookings_test <- clean_names(bookings_test)
```


# 6. KNN Model
```{r}
# 1. Building the Model:
library(class)
model2 <- knn(train = bookings_train[ ,-3], test = bookings_test[ ,-3], cl = bookings_train_labels, k = 35)

# 2. Model Evaluation
## With the KNN Model we obtain an accuracy of 77%
confusionMatrix(as.factor(model2), as.factor(bookings_test_labels))
```

# 7. SVM Model
```{r}
# 1. Building the Model: Kernel = Vanilladot
library("e1071")
library(kernlab)

model3 <- ksvm(as.factor(is_canceled) ~ ., data = bookings_train, kernel = "vanilladot")
summary(model3)

# 2. Model Evaluation:
bookings_predictors <- predict(model3, bookings_test)
## With the SVM Model we obtain an accuracy of 80.67%.
confusionMatrix(bookings_predictors, as.factor(bookings_test_labels))

## We will try different kernels in order to see which one has a higher accuracy.

# 3. Building the Model: Kernel = polydot

model3.2 <- ksvm(as.factor(is_canceled)~., data = bookings_train, kernel = "polydot")

# 4. Model Evaluation:
bookings_predictors2 <- predict(model3.2, bookings_test)
## With the SVM Model we obtain an accuracy of 80.67%.
confusionMatrix(bookings_predictors2, as.factor(bookings_test_labels))
```

# 8. ANN Model
```{r}
# 1. Building the Model:
library(neuralnet)
model4 <- neuralnet(formula = is_canceled ~., data = bookings_train, linear.output = FALSE)
model4_results <- compute(model4, bookings_test[,-3])$net.result

# 2. Model Evaluation:
binary.is <- ifelse(model4_results > 0.35, 1, 0)
## With the ANN Model we obtain an accuracy of 78.67%.
confusionMatrix(as.factor(binary.is), as.factor(bookings_test$is_canceled))

# 3. Model Improvement:
model4.2 <- neuralnet(formula = is_canceled ~., data = bookings_train, linear.output = FALSE, hidden = 4)
model4.2_results <- compute(model4.2, bookings_test[,-3])$net.result
summary(model4.2_results)

# 4. Model Evaluation:
binary.is2 <- ifelse(model4.2_results > 0.35, 1, 0)
## By improving the model we obtain a 78.33% accuracy.
confusionMatrix(as.factor(binary.is2), as.factor(bookings_test$is_canceled))
```

# 9. Decisions Trees
```{r}
# 1. Building the model:
library(C50)
model5 <- C5.0(bookings_train[-3], as.factor(bookings_train$is_canceled))
predict_m5 <- predict(model5, bookings_test)

# 2. Model Evaluation:
## We obtain a 79.33% accuracy.
confusionMatrix(predict_m5, as.factor(bookings_test_labels))

# 3. Improving the model:
## We'll start by setting trails = 10, as it is suggested that it may reduce error rates about 25%. 
model5.2 <- C5.0(bookings_train[-3], as.factor(bookings_train$is_canceled), trials = 10)
predict_m5.2 <- predict(model5.2, bookings_test)

# 4. Model Evaluation: 
## By improving the model we obtain a 82.33% accuracy.
confusionMatrix(predict_m5.2, as.factor(bookings_test_labels))

```

## 10. Model combination by voting
```{r}
combined <- data.frame(bookings_predictors, binary.is, predict_m5.2, bookings_test$is_canceled)

#Converting all factors into numeric forms for voting analysis
bookings_predictors_n <- as.numeric(bookings_predictors2)
binary.is_n <- as.numeric(binary.is2)
predict_m5.2_n <- as.numeric(predict_m5.2)

newcombined <- data.frame(bookings_predictors_n, binary.is_n, predict_m5.2_n, bookings_test$is_canceled)

newcombined$voting <- ifelse(bookings_predictors_n + binary.is_n + predict_m5.2_n > 2, 1,0)
newcombined$voting <- factor(newcombined$voting, levels = c(0,1), labels = c("no","yes"))
newcombined$bookings_test.is_canceled <- factor(newcombined$bookings_test.is_canceled, levels = c(0,1), labels = c("no","yes"))

agreement_all <- newcombined$voting == newcombined$bookings_test.is_canceled
str(newcombined)
confusionMatrix(newcombined$voting, newcombined$bookings_test.is_canceled)
```

