---
title: "Class22"
author: "Jan Láža"
date: "4/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data <- read.csv("census.csv")
#we need to rename the columns - there is a hint below but it does not match the columns right 
colnames(data) = c("age",
"class of worker", 
"industry code", 
"occupation code", 
"adjusted gross income", 
"education", 
"wage per hour", 
"enrolled in edu inst last wk ", 
"marital status ", 
"major industry code", 
"major occupation code", 
"race ", 
"hispanic Origin", 
"sex ", 
"member of a labor union ", 
"reason for unemployment ", 
"full or part time employment stat ", 
"capital gains ", 
"capital losses ", 
"divdends from stocks ", 
"federal income tax liability ", 
"tax filer status ", 
"region of previous residence ", 
"state of previous residence ", 
"detailed household and family stat ", 
"detailed household summary in household ", 
"instance weight ", 
"migration code-change in msa ", 
"migration code-change in reg ", 
"migration code-move within reg ", 
"live in this house 1 year ago ", 
"migration prev res in sunbelt", 
"num persons worked for employer ", 
"family members under 18 ", 
"total person earnings ", 
"country of birth father ", 
"country of birth mother ", 
"country of birth self ", 
"citizenship ", 
"total person income", 
"own business or self employed ", 
"taxable income amount ")
str(data)
col
```

